apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: holderforge-backend-output
  namespace: holderforge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
